#!/bin/sh
echo "Orbi(s) non sufficit"

if [ ! -d LOCAL_DIR ]; then
  mkdir LOCAL_DIR
fi
if ( mount | grep LOCAL_DIR ); then
  echo LOCAL_DIR is already mounted
else
  mount LOCAL_DISK LOCAL_DIR
fi

until [ -e LOCAL_DIR/init/00-null ]; do
  sleep 2
done

find -L LOCAL_DIR/init/ -type f -exec sh -c "echo running{}; {} &"  \;
